/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartenariatsRouteImport } from './routes/partenariats'
import { Route as GilberteRouteImport } from './routes/gilberte'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompagnieRouteImport } from './routes/compagnie'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'

const PartenariatsRoute = PartenariatsRouteImport.update({
  id: '/partenariats',
  path: '/partenariats',
  getParentRoute: () => rootRouteImport,
} as any)
const GilberteRoute = GilberteRouteImport.update({
  id: '/gilberte',
  path: '/gilberte',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompagnieRoute = CompagnieRouteImport.update({
  id: '/compagnie',
  path: '/compagnie',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/compagnie': typeof CompagnieRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/gilberte': typeof GilberteRoute
  '/partenariats': typeof PartenariatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/compagnie': typeof CompagnieRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/gilberte': typeof GilberteRoute
  '/partenariats': typeof PartenariatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/compagnie': typeof CompagnieRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/gilberte': typeof GilberteRoute
  '/partenariats': typeof PartenariatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/compagnie'
    | '/contact'
    | '/equipe'
    | '/gilberte'
    | '/partenariats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/compagnie'
    | '/contact'
    | '/equipe'
    | '/gilberte'
    | '/partenariats'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/compagnie'
    | '/contact'
    | '/equipe'
    | '/gilberte'
    | '/partenariats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  CompagnieRoute: typeof CompagnieRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRoute
  GilberteRoute: typeof GilberteRoute
  PartenariatsRoute: typeof PartenariatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partenariats': {
      id: '/partenariats'
      path: '/partenariats'
      fullPath: '/partenariats'
      preLoaderRoute: typeof PartenariatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gilberte': {
      id: '/gilberte'
      path: '/gilberte'
      fullPath: '/gilberte'
      preLoaderRoute: typeof GilberteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compagnie': {
      id: '/compagnie'
      path: '/compagnie'
      fullPath: '/compagnie'
      preLoaderRoute: typeof CompagnieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  CompagnieRoute: CompagnieRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRoute,
  GilberteRoute: GilberteRoute,
  PartenariatsRoute: PartenariatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
